### ISSUE TITLE
Making use of other dns proxies for certain zones

### ISSUE THREAD

**Issue by khavishbhundoo** [jmhale/dns-proxy#2]
Hello, 

I learnt a lot from your tutorial about [dns proxy](https://halesec.com/2017/01/02/building-your-own-dns-proxy-part-1.html).I want to use other dns servers for certain sites that georestrict to other countries.

How can  i add a new domain in the `zones.override` and tell bind to use another dns server(located in another) for this domain.

With SmartDNSProxy, you just change your dns once and you can bypass georestriction for various services located in different countries

**Comment by jmhale** [comment]
@khavishbhundoo What you're looking for is called "conditional forwarding" or adding a "forward zone", in bind9 vernacular.

An example of how to add a zone in this manner is given here: https://serverfault.com/questions/409190/how-to-properly-configure-bind-forward-zone-for-an-internal-dns-server#718162
